from django.urls import path
from .views import (
    captcha_challenge,
    google_oauth,
    health,
    metrics,
    login,
    openapi_json,
    orders,
    pay_order,
    refresh_token,
    redoc_ui,
    register,
    request_2fa,
    retention_summary,
    swagger_ui,
    track_event,
    verify_2fa,
)

urlpatterns = [
    path('health/', health),
    path('orders/', orders),
    path('orders/<int:order_id>/pay/', pay_order),
    path('register/', register),
    path('login/', login),
    path('captcha/', captcha_challenge),
    path('refresh-token/', refresh_token),
    path('oauth/google/', google_oauth),
    path('events/', track_event),
    path('analytics/retention/', retention_summary),
    path('metrics/', metrics),
    path('openapi.json', openapi_json),
    path('docs/swagger/', swagger_ui),
    path('docs/redoc/', redoc_ui),
    path('2fa/request/', request_2fa),
    path('2fa/verify/', verify_2fa),
]
