// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2YbeJO67sl95LB6CSXHcTDAwvDiK-30',
    appId: '1:960392383399:web:7c7f5b4a9f40ea56dec482',
    messagingSenderId: '960392383399',
    projectId: 'pathway-b0a32',
    authDomain: 'pathway-b0a32.firebaseapp.com',
    storageBucket: 'pathway-b0a32.firebasestorage.app',
    measurementId: 'G-XY317HK34J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyUhHo0eKKi1HNcrGthMeSI3p9o0xJOXo',
    appId: '1:960392383399:android:535e54cbcc2b9803dec482',
    messagingSenderId: '960392383399',
    projectId: 'pathway-b0a32',
    storageBucket: 'pathway-b0a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJ2SWlRBWQcyhjIgON-QNcrX8I_3uubA',
    appId: '1:960392383399:ios:a3cbf8af224af453dec482',
    messagingSenderId: '960392383399',
    projectId: 'pathway-b0a32',
    storageBucket: 'pathway-b0a32.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJ2SWlRBWQcyhjIgON-QNcrX8I_3uubA',
    appId: '1:960392383399:ios:a3cbf8af224af453dec482',
    messagingSenderId: '960392383399',
    projectId: 'pathway-b0a32',
    storageBucket: 'pathway-b0a32.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa2YbeJO67sl95LB6CSXHcTDAwvDiK-30',
    appId: '1:960392383399:web:e292d8899884748cdec482',
    messagingSenderId: '960392383399',
    projectId: 'pathway-b0a32',
    authDomain: 'pathway-b0a32.firebaseapp.com',
    storageBucket: 'pathway-b0a32.firebasestorage.app',
    measurementId: 'G-WPDLYJNCTW',
  );
}
