# Generated by Django 6.0.3 on 2026-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportorder',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='service_type',
            field=models.CharField(default='airport', max_length=50),
        ),
    ]
