# Generated by Django 6.0.3 on 2026-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airportorder_arrival_date_airportorder_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportorder',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
