# Generated by Django 6.0.3 on 2026-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_airportorder_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportorder',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='order_status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='airportorder',
            name='order_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
