# Generated by Django 4.2.30 on 2026-06-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_created_at_order_updated_at_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
